// Phosphor icons (docs/09 § Iconography), re-exported so every screen uses one set.
export {
  ArrowRight,
  ArrowSquareOut,
  Bell,
  CaretDown,
  CaretRight,
  ChartBar,
  CheckCircle,
  Clock,
  Copy,
  Database,
  FunnelSimple,
  Gauge,
  GearSix,
  House,
  IdentificationBadge,
  Kanban,
  Key,
  List,
  LockKeyOpen,
  MagnifyingGlass,
  Moon,
  Plugs,
  SignOut,
  SlidersHorizontal,
  Sparkle,
  Target,
  Tray,
  TreeStructure,
  Upload,
  UserCircle,
  Users,
  UsersThree,
  Warning,
  WaveSine,
  X,
} from "@phosphor-icons/react/dist/ssr";
export type { Icon as IconType } from "@phosphor-icons/react";
