// The one place icons come from (docs/09-design-system.md § Icons). Phosphor, regular weight.
// Exported under the product's own role names so screens don't depend on an icon family;
// swapping families means editing this file only. The /ssr entry works in Server Components.
export type { Icon as IconType } from "@phosphor-icons/react";
export {
  AlarmIcon as AlarmClock,
  WarningIcon as AlertTriangle,
  ArrowDownRightIcon as ArrowDownRight,
  ArrowUpRightIcon as ArrowUpRight,
  AtIcon as AtSign,
  CurrencyCircleDollarIcon as BadgeDollarSign,
  BedIcon as BedDouble,
  BellIcon as Bell,
  CalendarDotsIcon as CalendarDays,
  CalendarPlusIcon as CalendarPlus,
  CalendarBlankIcon as CalendarRange,
  CheckIcon as Check,
  CaretDownIcon as ChevronDown,
  CaretLeftIcon as ChevronLeft,
  CaretRightIcon as ChevronRight,
  CheckCircleIcon as CircleCheck,
  QuestionIcon as CircleHelp,
  XCircleIcon as CircleX,
  ClipboardTextIcon as ClipboardCheck,
  FileTextIcon as FileText,
  GitPullRequestIcon as GitPullRequestArrow,
  DotsSixVerticalIcon as GripVertical,
  KanbanIcon as KanbanSquare,
  StackIcon as Layers,
  SquaresFourIcon as LayoutDashboard,
  ListIcon as List,
  CircleNotchIcon as Loader2,
  SignOutIcon as LogOut,
  ListIcon as Menu,
  ChatsCircleIcon as MessagesSquare,
  MinusIcon as Minus,
  PlusIcon as Plus,
  ScrollIcon as ScrollText,
  MagnifyingGlassIcon as Search,
  PaperPlaneRightIcon as SendHorizontal,
  TrashIcon as Trash2,
  UserIcon as UserRound,
  UsersIcon as Users,
  XIcon as X,
  SidebarSimpleIcon as PanelLeftOpen,
  SidebarSimpleIcon as PanelLeftClose,
  ImageIcon as ImageSquare,
  TicketIcon as Ticket,
  BuildingsIcon as Building2,
  TruckIcon as Truck,
  ChartBarIcon as FileBarChart,
  GearSixIcon as Settings,
} from "@phosphor-icons/react/ssr";
