// Generated by scripts/gen-imagery.mjs from scripts/imagery-manifest.json. Do not edit by hand.
// Photos: Unsplash License (free for commercial use, no attribution required). Credits: docs/image-credits.md.

export type Photo = { key: string; src: string; label: string; alt: string; focal: string; credit: string; sourceUrl: string };

export const WALLPAPERS: readonly Photo[] = [
  { key: "ballroom", src: "/images/wallpapers/ballroom.webp", label: "Grand ballroom", alt: "Grand ballroom with chandeliers and rows of chairs", focal: "50% 72%", credit: "Sergei Kondalov", sourceUrl: "https://unsplash.com/photos/FKLXn1mw3Bg" },
  { key: "gala", src: "/images/wallpapers/gala.webp", label: "Gala hall", alt: "Elegant ballroom with long tables, chandeliers and tall columns", focal: "50% 60%", credit: "Lucas T Photography", sourceUrl: "https://unsplash.com/photos/T5v5i67QYGk" },
  { key: "stage", src: "/images/wallpapers/stage.webp", label: "Conference stage", alt: "A podium with a microphone on an empty stage", focal: "50% 45%", credit: "Wesley Tingey", sourceUrl: "https://unsplash.com/photos/bWRX_obQAl8" },
  { key: "banquet", src: "/images/wallpapers/banquet.webp", label: "Banquet", alt: "Event space set with round tables for dining", focal: "50% 55%", credit: "Filip Rankovic Grobgaard", sourceUrl: "https://unsplash.com/photos/EJQnHC6GEe8" },
  { key: "skyline", src: "/images/wallpapers/skyline.webp", label: "City at night", alt: "A view of a city at night from across the water", focal: "50% 62%", credit: "Raf Winterpacht", sourceUrl: "https://unsplash.com/photos/zpS-yPj1qjU" },
];

export const COVERS: readonly Photo[] = [
  { key: "lisbon", src: "/images/covers/lisbon.webp", label: "Lisbon", alt: "Lisbon with the bridge in the background", focal: "50% 45%", credit: "imren tutuncu", sourceUrl: "https://unsplash.com/photos/xoUrDP3glkU" },
  { key: "chicago", src: "/images/covers/chicago.webp", label: "Chicago", alt: "Chicago skyline across Lake Michigan", focal: "50% 50%", credit: "Jeff Brown", sourceUrl: "https://unsplash.com/photos/xOj6_Ha1_R8" },
  { key: "london", src: "/images/covers/london.webp", label: "London", alt: "London skyline and the Thames at low sun", focal: "50% 50%", credit: "Alev Takil", sourceUrl: "https://unsplash.com/photos/7ojyp-IXW7w" },
  { key: "san-francisco", src: "/images/covers/san-francisco.webp", label: "San Francisco", alt: "The Bay Bridge illuminated at night", focal: "50% 50%", credit: "Jack Nagz", sourceUrl: "https://unsplash.com/photos/aL4PfTXz8S8" },
  { key: "barcelona", src: "/images/covers/barcelona.webp", label: "Barcelona", alt: "Panoramic view of Barcelona with the Sagrada Família", focal: "50% 62%", credit: "Carlos Ibáñez", sourceUrl: "https://unsplash.com/photos/PAKlGZNVUQM" },
  { key: "napa", src: "/images/covers/napa.webp", label: "Vineyard", alt: "A vineyard with rows of vines and mountains", focal: "50% 55%", credit: "Daniel Salgado", sourceUrl: "https://unsplash.com/photos/MF2KORFe1OE" },
  { key: "resort", src: "/images/covers/resort.webp", label: "Resort pool", alt: "Lounge chairs and an umbrella near a swimming pool", focal: "50% 50%", credit: "Ahmad Ajmi", sourceUrl: "https://unsplash.com/photos/t6Le7895iuk" },
  { key: "podium", src: "/images/covers/podium.webp", label: "Podium stage", alt: "A podium with a microphone on a stage", focal: "50% 45%", credit: "Wesley Tingey", sourceUrl: "https://unsplash.com/photos/bWRX_obQAl8" },
  { key: "theatre-seats", src: "/images/covers/theatre-seats.webp", label: "Auditorium", alt: "Empty red seats in a modern auditorium", focal: "50% 50%", credit: "Declan Sun", sourceUrl: "https://unsplash.com/photos/zWNyOzsWqDc" },
  { key: "theatre-stage", src: "/images/covers/theatre-stage.webp", label: "Theatre", alt: "Empty theatre auditorium with stage and seating", focal: "50% 50%", credit: "ARTO SURAJ", sourceUrl: "https://unsplash.com/photos/kTT8mJ5pPpc" },
  { key: "round-tables", src: "/images/covers/round-tables.webp", label: "Banquet rounds", alt: "Event space set with round tables for dining", focal: "50% 50%", credit: "Filip Rankovic Grobgaard", sourceUrl: "https://unsplash.com/photos/EJQnHC6GEe8" },
  { key: "banquet-rounds", src: "/images/covers/banquet-rounds.webp", label: "Gala dinner", alt: "Banquet hall set for an event with round tables", focal: "50% 50%", credit: "Matt Benson", sourceUrl: "https://unsplash.com/photos/cQxEJoQZ_-E" },
  { key: "long-table", src: "/images/covers/long-table.webp", label: "Private dining", alt: "Ornate dining hall with a long table and chandeliers", focal: "50% 50%", credit: "SOHAM BANERJEE", sourceUrl: "https://unsplash.com/photos/26kcgxYv3LA" },
  { key: "ballroom-tables", src: "/images/covers/ballroom-tables.webp", label: "Ballroom dinner", alt: "Ballroom with tables prepared for a formal event", focal: "50% 50%", credit: "Manya Sivanandam", sourceUrl: "https://unsplash.com/photos/qePRtRzOUf0" },
  { key: "grand-ballroom", src: "/images/covers/grand-ballroom.webp", label: "Ballroom", alt: "Grand ballroom with ornate chandeliers and polished floor", focal: "50% 50%", credit: "mana5280", sourceUrl: "https://unsplash.com/photos/krAQD5gGBSM" },
  { key: "ballroom-stage", src: "/images/covers/ballroom-stage.webp", label: "Theatre ballroom", alt: "Ornate ballroom with a stage and balconies", focal: "50% 50%", credit: "Michael D Beckwith", sourceUrl: "https://unsplash.com/photos/n0Qne2MZWZM" },
  { key: "hotel-lobby", src: "/images/covers/hotel-lobby.webp", label: "Hotel lobby", alt: "Lobby of a luxury hotel with pendant lights", focal: "50% 40%", credit: "Haripriya K", sourceUrl: "https://unsplash.com/photos/mPuv7limVSM" },
];

export const PLAIN = "plain";
export const wallpaperKeys = [PLAIN, ...WALLPAPERS.map((w) => w.key)] as const;
export const coverKeys = COVERS.map((c) => c.key);

export function findWallpaper(key: string | null | undefined): Photo | null {
  return WALLPAPERS.find((w) => w.key === key) ?? null;
}

export function findCover(key: string | null | undefined): Photo | null {
  return COVERS.find((c) => c.key === key) ?? null;
}
