// Generates src/config/imagery.ts and docs/image-credits.md from scripts/imagery-manifest.json.
// Run after changing the manifest: node scripts/gen-imagery.mjs
import { readFileSync, writeFileSync } from "node:fs";

const m = JSON.parse(readFileSync(new URL("./imagery-manifest.json", import.meta.url), "utf8"));
const entry = (kind) => (i) =>
  `  { key: ${JSON.stringify(i.key)}, src: "/images/${kind}/${i.key}.webp", label: ${JSON.stringify(i.label)}, alt: ${JSON.stringify(i.description)}, focal: ${JSON.stringify(i.focal ?? "50% 50%")}, credit: ${JSON.stringify(i.photographer)}, sourceUrl: "https://unsplash.com/photos/${i.id}" },`;

writeFileSync(
  "src/config/imagery.ts",
  `// Generated by scripts/gen-imagery.mjs from scripts/imagery-manifest.json. Do not edit by hand.
// Photos: Unsplash License (free for commercial use, no attribution required). Credits: docs/image-credits.md.

export type Photo = { key: string; src: string; label: string; alt: string; focal: string; credit: string; sourceUrl: string };

export const WALLPAPERS: readonly Photo[] = [
${m.wallpapers.map(entry("wallpapers")).join("\n")}
];

export const COVERS: readonly Photo[] = [
${m.covers.map(entry("covers")).join("\n")}
];

export const PLAIN = "plain";
export const wallpaperKeys = [PLAIN, ...WALLPAPERS.map((w) => w.key)] as const;
export const coverKeys = COVERS.map((c) => c.key);

export function findWallpaper(key: string | null | undefined): Photo | null {
  return WALLPAPERS.find((w) => w.key === key) ?? null;
}

export function findCover(key: string | null | undefined): Photo | null {
  return COVERS.find((c) => c.key === key) ?? null;
}
`,
);

const row = (kind) => (i) =>
  `| ${i.label} | \`public/images/${kind}/${i.key}.webp\` | ${i.photographer} | [unsplash.com/photos/${i.id}](https://unsplash.com/photos/${i.id}) |${i.note ? ` ${i.note}` : ""}`;
writeFileSync(
  "docs/image-credits.md",
  `# Image credits

Generated from \`scripts/imagery-manifest.json\` by \`scripts/gen-imagery.mjs\`.

**Licence:** ${m.licence} Attribution is not required, but it is recorded here anyway.

**Review:** ${m.review}

To change the set, edit the manifest, delete the file you are replacing, then run \`node scripts/fetch-imagery.mjs\` and \`node scripts/gen-imagery.mjs\`. **Look at every new photo before committing it.** Note that \`hotel-lobby\` was cropped by hand after download; re-fetching it brings back the uncropped original.

## Wallpapers

| Label | File | Photographer | Source | Note |
|---|---|---|---|---|
${m.wallpapers.map(row("wallpapers")).join("\n")}

## Event covers

| Label | File | Photographer | Source | Note |
|---|---|---|---|---|
${m.covers.map(row("covers")).join("\n")}
`,
);
console.log(`catalogue: ${m.wallpapers.length} wallpapers, ${m.covers.length} covers`);
